import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateWorkflowDefinition1785812038993 implements MigrationInterface {
    name = 'UpdateWorkflowDefinition1785812038993'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP CONSTRAINT "FK_workflow_nodes_template"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP CONSTRAINT "FK_workflow_transitions_source"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP CONSTRAINT "FK_workflow_transitions_target"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workflow_nodes_template_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workflow_transitions_source"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_tenant_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_is_read"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_created_at"`);
        await queryRunner.query(`CREATE TABLE "workflow_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "definition_id" uuid NOT NULL, "version_number" integer NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'draft', "changelog" text, "published_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a84eb8dc6065f33ce4b1447955f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workflow_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "key" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "resource_type" character varying(100) NOT NULL DEFAULT 'work_order', "status" character varying(50) NOT NULL DEFAULT 'draft', "current_version_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4f92fadfc5fb722f080ceaec272" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "template_id"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "sla_minutes"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "form_schema"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "required_permissions"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "position_x"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "position_y"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "step_key"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "assignee_type"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "assignee_value"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "assignment_strategy"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "source_node_id"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "target_node_id"`);
        await queryRunner.query(`ALTER TABLE "work_order_logs" ADD "metadata" jsonb NOT NULL DEFAULT '{}' ::jsonb`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "version_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "key" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "config" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "ui_position" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "assignees" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "version_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "source_key" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "target_key" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "action_key" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "sort_order" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sites" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "enabled_modules" SET DEFAULT '["core","administration","e-office","digital-signature","organization"]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "settings" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "organization_units" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "positions" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "submission_actions" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "submissions" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "signature_requests" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "label"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "label" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "condition"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "condition" jsonb`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "payload" SET DEFAULT '{}' ::jsonb`);
        await queryRunner.query(`CREATE INDEX "IDX_d93ddd7e1b890535ecafbb334e" ON "notifications" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f12148ce379462ebbb4d06cc13" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_77ee7b06d6f802000c0846f3a5" ON "notifications" ("created_at") `);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD CONSTRAINT "FK_8449fdf0367b3e6e38f651b4974" FOREIGN KEY ("version_id") REFERENCES "workflow_versions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD CONSTRAINT "FK_045c9d531d59cad970506339215" FOREIGN KEY ("version_id") REFERENCES "workflow_versions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_versions" ADD CONSTRAINT "FK_40d0fd77a39f4c7b60adc43abd0" FOREIGN KEY ("definition_id") REFERENCES "workflow_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD CONSTRAINT "FK_e38d7b56ee3d433e991f5ab3f9e" FOREIGN KEY ("current_version_id") REFERENCES "workflow_versions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP CONSTRAINT "FK_e38d7b56ee3d433e991f5ab3f9e"`);
        await queryRunner.query(`ALTER TABLE "workflow_versions" DROP CONSTRAINT "FK_40d0fd77a39f4c7b60adc43abd0"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP CONSTRAINT "FK_045c9d531d59cad970506339215"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP CONSTRAINT "FK_8449fdf0367b3e6e38f651b4974"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77ee7b06d6f802000c0846f3a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f12148ce379462ebbb4d06cc13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d93ddd7e1b890535ecafbb334e"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "payload" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "condition"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "condition" character varying(30) NOT NULL DEFAULT 'DEFAULT'`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "label"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "label" character varying(80)`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "name" character varying(220) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "type" character varying(20) NOT NULL DEFAULT 'task'`);
        await queryRunner.query(`ALTER TABLE "signature_requests" ALTER COLUMN "metadata" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "submissions" ALTER COLUMN "metadata" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "submission_actions" ALTER COLUMN "metadata" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "positions" ALTER COLUMN "metadata" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "organization_units" ALTER COLUMN "metadata" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "settings" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "enabled_modules" SET DEFAULT '["core", "administration", "e-office", "digital-signature", "organization"]'`);
        await queryRunner.query(`ALTER TABLE "sites" ALTER COLUMN "metadata" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "sort_order"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "action_key"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "target_key"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "source_key"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" DROP COLUMN "version_id"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "assignees"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "ui_position"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "config"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" DROP COLUMN "version_id"`);
        await queryRunner.query(`ALTER TABLE "work_order_logs" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "target_node_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD "source_node_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "assignment_strategy" character varying(10) NOT NULL DEFAULT 'ANY'`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "assignee_value" character varying(120)`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "assignee_type" character varying(40)`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "step_key" character varying(80) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "position_y" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "position_x" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "required_permissions" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "form_schema" jsonb`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "sla_minutes" integer`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD "template_id" uuid NOT NULL`);
        await queryRunner.query(`DROP TABLE "workflow_definitions"`);
        await queryRunner.query(`DROP TABLE "workflow_versions"`);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_created_at" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_is_read" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_tenant_user" ON "notifications" ("tenant_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_workflow_transitions_source" ON "workflow_transitions" ("source_node_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_workflow_nodes_template_id" ON "workflow_nodes" ("template_id") `);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD CONSTRAINT "FK_workflow_transitions_target" FOREIGN KEY ("target_node_id") REFERENCES "workflow_nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_transitions" ADD CONSTRAINT "FK_workflow_transitions_source" FOREIGN KEY ("source_node_id") REFERENCES "workflow_nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_nodes" ADD CONSTRAINT "FK_workflow_nodes_template" FOREIGN KEY ("template_id") REFERENCES "workflow_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
