export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_RESET_PASSWORD: 'users.reset-password',
  ROLES_VIEW: 'roles.view',
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',
  ROLES_ASSIGN_PERMISSIONS: 'roles.assign-permissions',
  AUDIT_VIEW: 'audit.view',
  OPERATIONS_VIEW: 'operations.view',
  EOFFICE_VIEW: 'eoffice.view',
  TENANT_SETTINGS_VIEW: 'tenant-settings.view',
  TENANT_SETTINGS_UPDATE: 'tenant-settings.update',
  ORGANIZATION_VIEW: 'organization.view',
  ORGANIZATION_MANAGE: 'organization.manage',
  WORK_ITEMS_VIEW: 'work-items.view',
  SUBMISSIONS_VIEW: 'submissions.view',
  SUBMISSIONS_CREATE: 'submissions.create',
  SUBMISSIONS_UPDATE: 'submissions.update',
  SUBMISSIONS_SUBMIT: 'submissions.submit',
  SUBMISSIONS_REVIEW: 'submissions.review',
  SIGNATURES_VIEW: 'signatures.view',
  SIGNATURES_REQUEST: 'signatures.request',
  EQUIPMENT_VIEW: 'equipment.view',
  EQUIPMENT_CREATE: 'equipment.create',
  EQUIPMENT_UPDATE: 'equipment.update',
  EQUIPMENT_DELETE: 'equipment.delete',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_CREATE: 'inventory.create',
  INVENTORY_TRANSACTION: 'inventory.transaction',
  WORK_ORDER_VIEW: 'work_order.view',
  WORK_ORDER_CREATE: 'work_order.create',
  WORK_ORDER_UPDATE: 'work_order.update',
  MAINTENANCE_VIEW: 'maintenance.view',
  MAINTENANCE_CREATE: 'maintenance.create',
  MAINTENANCE_UPDATE: 'maintenance.update',
  MAINTENANCE_DELETE: 'maintenance.delete',
  // Workflow Engine
  WORKFLOW_VIEW: 'workflow.definition.view',
  WORKFLOW_CREATE: 'workflow.definition.create',
  WORKFLOW_UPDATE: 'workflow.definition.update',
  WORKFLOW_DELETE: 'workflow.definition.delete',
  WORKFLOW_EXECUTE: 'workflow.execute',
  WORKFLOW_REVIEW: 'work_order.review',
  // Notifications
  NOTIFICATIONS_VIEW: 'notifications.view',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATALOG: ReadonlyArray<{
  key: PermissionKey;
  name: string;
  group: string;
  description: string;
}> = [
  {
    key: PERMISSIONS.DASHBOARD_VIEW,
    name: 'Xem tổng quan',
    group: 'Tổng quan',
    description: 'Truy cập bảng điều khiển vận hành.',
  },
  {
    key: PERMISSIONS.USERS_VIEW,
    name: 'Xem người dùng',
    group: 'Người dùng',
    description: 'Xem danh sách và chi tiết người dùng.',
  },
  {
    key: PERMISSIONS.USERS_CREATE,
    name: 'Tạo người dùng',
    group: 'Người dùng',
    description: 'Tạo tài khoản mới.',
  },
  {
    key: PERMISSIONS.USERS_UPDATE,
    name: 'Cập nhật người dùng',
    group: 'Người dùng',
    description: 'Cập nhật thông tin, trạng thái và vai trò.',
  },
  {
    key: PERMISSIONS.USERS_DELETE,
    name: 'Xóa người dùng',
    group: 'Người dùng',
    description: 'Xóa tài khoản không còn sử dụng.',
  },
  {
    key: PERMISSIONS.USERS_RESET_PASSWORD,
    name: 'Đặt lại mật khẩu',
    group: 'Người dùng',
    description: 'Đặt mật khẩu mới theo yêu cầu quản trị.',
  },
  {
    key: PERMISSIONS.ROLES_VIEW,
    name: 'Xem vai trò',
    group: 'Vai trò & quyền',
    description: 'Xem vai trò và ma trận quyền.',
  },
  {
    key: PERMISSIONS.ROLES_CREATE,
    name: 'Tạo vai trò',
    group: 'Vai trò & quyền',
    description: 'Tạo vai trò động.',
  },
  {
    key: PERMISSIONS.ROLES_UPDATE,
    name: 'Cập nhật vai trò',
    group: 'Vai trò & quyền',
    description: 'Cập nhật tên và mô tả vai trò.',
  },
  {
    key: PERMISSIONS.ROLES_DELETE,
    name: 'Xóa vai trò',
    group: 'Vai trò & quyền',
    description: 'Xóa vai trò không phải hệ thống.',
  },
  {
    key: PERMISSIONS.ROLES_ASSIGN_PERMISSIONS,
    name: 'Gán quyền',
    group: 'Vai trò & quyền',
    description: 'Thay đổi quyền của vai trò.',
  },
  {
    key: PERMISSIONS.AUDIT_VIEW,
    name: 'Xem nhật ký',
    group: 'Nhật ký',
    description: 'Theo dõi các thay đổi quản trị.',
  },
  {
    key: PERMISSIONS.OPERATIONS_VIEW,
    name: 'Xem vận hành',
    group: 'Vận hành',
    description: 'Truy cập các màn hình vận hành nhà máy được cấp quyền.',
  },
  {
    key: PERMISSIONS.EOFFICE_VIEW,
    name: 'Xem eOffice',
    group: 'eOffice',
    description: 'Truy cập không gian eOffice và các phân hệ được cấp quyền.',
  },
  {
    key: PERMISSIONS.TENANT_SETTINGS_VIEW,
    name: 'Xem cấu hình doanh nghiệp',
    group: 'Quản trị doanh nghiệp',
    description:
      'Xem thương hiệu, locale, múi giờ và nhà máy của doanh nghiệp.',
  },
  {
    key: PERMISSIONS.TENANT_SETTINGS_UPDATE,
    name: 'Cập nhật cấu hình doanh nghiệp',
    group: 'Quản trị doanh nghiệp',
    description: 'Cập nhật cấu hình vận hành và nhận diện doanh nghiệp.',
  },
  {
    key: PERMISSIONS.ORGANIZATION_VIEW,
    name: 'Xem cơ cấu tổ chức',
    group: 'Quản trị doanh nghiệp',
    description: 'Xem phòng ban, đơn vị và chức danh.',
  },
  {
    key: PERMISSIONS.ORGANIZATION_MANAGE,
    name: 'Quản lý cơ cấu tổ chức',
    group: 'Quản trị doanh nghiệp',
    description: 'Tạo, cập nhật và ngừng sử dụng đơn vị, chức danh.',
  },
  {
    key: PERMISSIONS.WORK_ITEMS_VIEW,
    name: 'Xem công việc của tôi',
    group: 'Điều hành',
    description: 'Xem các hồ sơ và nhiệm vụ đang chờ xử lý.',
  },
  {
    key: PERMISSIONS.SUBMISSIONS_VIEW,
    name: 'Xem hồ sơ trình ký',
    group: 'E-Office',
    description: 'Xem danh sách và chi tiết hồ sơ trong phạm vi doanh nghiệp.',
  },
  {
    key: PERMISSIONS.SUBMISSIONS_CREATE,
    name: 'Tạo hồ sơ trình ký',
    group: 'E-Office',
    description: 'Tạo hồ sơ trình ký mới.',
  },
  {
    key: PERMISSIONS.SUBMISSIONS_UPDATE,
    name: 'Cập nhật hồ sơ trình ký',
    group: 'E-Office',
    description: 'Cập nhật hồ sơ đang ở trạng thái cho phép chỉnh sửa.',
  },
  {
    key: PERMISSIONS.SUBMISSIONS_SUBMIT,
    name: 'Gửi hồ sơ trình ký',
    group: 'E-Office',
    description: 'Gửi hồ sơ vào luồng phê duyệt.',
  },
  {
    key: PERMISSIONS.SUBMISSIONS_REVIEW,
    name: 'Phê duyệt hồ sơ',
    group: 'E-Office',
    description: 'Phê duyệt hoặc trả lại hồ sơ được phân công.',
  },
  {
    key: PERMISSIONS.SIGNATURES_VIEW,
    name: 'Xem yêu cầu ký số',
    group: 'Chữ ký số',
    description: 'Xem trạng thái các yêu cầu ký số.',
  },
  {
    key: PERMISSIONS.SIGNATURES_REQUEST,
    name: 'Tạo yêu cầu ký số',
    group: 'Chữ ký số',
    description: 'Đưa hồ sơ đã phê duyệt vào hàng đợi ký số.',
  },
  {
    key: PERMISSIONS.EQUIPMENT_VIEW,
    name: 'Xem thiết bị',
    group: 'Kỹ thuật',
    description: 'Xem danh sách và thông tin thiết bị.',
  },
  {
    key: PERMISSIONS.EQUIPMENT_CREATE,
    name: 'Tạo thiết bị',
    group: 'Kỹ thuật',
    description: 'Thêm mới thiết bị vào hệ thống.',
  },
  {
    key: PERMISSIONS.EQUIPMENT_UPDATE,
    name: 'Cập nhật thiết bị',
    group: 'Kỹ thuật',
    description: 'Cập nhật lý lịch và thông số thiết bị.',
  },
  {
    key: PERMISSIONS.EQUIPMENT_DELETE,
    name: 'Xóa thiết bị',
    group: 'Kỹ thuật',
    description: 'Xóa thiết bị khỏi hệ thống.',
  },
  {
    key: PERMISSIONS.INVENTORY_VIEW,
    name: 'Xem kho và vật tư',
    group: 'Kho & Vật tư',
    description: 'Xem danh sách vật tư, tồn kho và lịch sử giao dịch.',
  },
  {
    key: PERMISSIONS.INVENTORY_CREATE,
    name: 'Tạo vật tư/kho',
    group: 'Kho & Vật tư',
    description: 'Khai báo vật tư và kho bãi mới.',
  },
  {
    key: PERMISSIONS.INVENTORY_TRANSACTION,
    name: 'Giao dịch Nhập/Xuất',
    group: 'Kho & Vật tư',
    description: 'Thực hiện nhập xuất kho vật tư.',
  },
  {
    key: PERMISSIONS.WORK_ORDER_VIEW,
    name: 'Xem phiếu công việc',
    group: 'Kỹ thuật',
    description: 'Xem danh sách và chi tiết phiếu sự cố/công việc.',
  },
  {
    key: PERMISSIONS.WORK_ORDER_CREATE,
    name: 'Tạo phiếu công việc',
    group: 'Kỹ thuật',
    description: 'Tạo phiếu sự cố và yêu cầu bảo trì.',
  },
  {
    key: PERMISSIONS.WORK_ORDER_UPDATE,
    name: 'Cập nhật phiếu',
    group: 'Kỹ thuật',
    description: 'Cập nhật trạng thái, phân công và đóng phiếu.',
  },
  {
    key: PERMISSIONS.MAINTENANCE_VIEW,
    name: 'Xem kế hoạch bảo trì',
    group: 'Kỹ thuật',
    description: 'Xem danh sách và chi tiết các kế hoạch bảo trì thiết bị.',
  },
  {
    key: PERMISSIONS.MAINTENANCE_CREATE,
    name: 'Tạo kế hoạch bảo trì',
    group: 'Kỹ thuật',
    description: 'Tạo mới kế hoạch bảo trì định kỳ cho thiết bị.',
  },
  {
    key: PERMISSIONS.MAINTENANCE_UPDATE,
    name: 'Cập nhật kế hoạch',
    group: 'Kỹ thuật',
    description: 'Cập nhật nội dung và chu kỳ của kế hoạch bảo trì.',
  },
  {
    key: PERMISSIONS.MAINTENANCE_DELETE,
    name: 'Xóa kế hoạch bảo trì',
    group: 'Kỹ thuật',
    description: 'Xóa bỏ các kế hoạch bảo trì khỏi hệ thống.',
  },
  {
    key: PERMISSIONS.WORKFLOW_VIEW,
    name: 'Xem mẫu quy trình',
    group: 'Quy trình',
    description: 'Xem danh sách và sơ đồ mẫu quy trình (Mini-map).',
  },
  {
    key: PERMISSIONS.WORKFLOW_CREATE,
    name: 'Tạo mẫu quy trình',
    group: 'Quy trình',
    description: 'Thiết kế và tạo mới mẫu quy trình.',
  },
  {
    key: PERMISSIONS.WORKFLOW_UPDATE,
    name: 'Cập nhật mẫu quy trình',
    group: 'Quy trình',
    description: 'Chỉnh sửa cấu hình node, tác nhân và biểu mẫu.',
  },
  {
    key: PERMISSIONS.WORKFLOW_DELETE,
    name: 'Xóa mẫu quy trình',
    group: 'Quy trình',
    description: 'Xóa các mẫu quy trình không còn sử dụng.',
  },
  {
    key: PERMISSIONS.WORKFLOW_EXECUTE,
    name: 'Thực thi quy trình',
    group: 'Quy trình',
    description: 'Hoàn thành hoặc từ chối các bước trong luồng quy trình.',
  },
  {
    key: PERMISSIONS.WORKFLOW_REVIEW,
    name: 'Kiểm tra & nghiệm thu',
    group: 'Kỹ thuật',
    description: 'Review và nghiệm thu kết quả công việc kỹ thuật.',
  },
  {
    key: PERMISSIONS.NOTIFICATIONS_VIEW,
    name: 'Xem thông báo',
    group: 'Thông báo',
    description: 'Nhận và xem thông báo giao việc, nhắc SLA trong hệ thống.',
  },
];
